### ISSUE TITLE
invalid tag error cannot be caught?

### ISSUE THREAD

**Issue by jdutchak** [paulmillr/noble-ciphers#16]
updated from 0.1.4 to 0.4.0 now i keep getting invalid tag error - has something changed here? what should I look for?

 Error: invalid tag
      at Object.decrypt (node_modules/@noble/ciphers/src/chacha.ts:266:48)

**Comment by paulmillr** [comment]
any specific test vector you could share?

**Comment by jdutchak** [comment]
gives hard error that some apps cannot recover from ie Preact with ViteJS --- vs just wrong or invalid tag error depending on lib ver 0.1.4 or 0.4.0 

```
const d =  XChaCha20Poly1305.decrypt({
              data  : new Uint8Array(10),
              key   : new Uint8Array(32),
              nonce : new Uint8Array(24),
              tag   : new Uint8Array(16)
            })
console.log(d) 

```

**Comment by paulmillr** [comment]
Works fine for me with 0.4.0, the error is correctly catched:

```js
import { xchacha20poly1305 } from '@noble/ciphers/chacha';
const key = new Uint8Array(32);
const nonce = new Uint8Array(24);
const chacha = xchacha20poly1305(key, nonce);
try {
  const data_ = chacha.decrypt(new Uint8Array(32));
} catch (error) {
  // console.log('log', error)
}
```

**Comment by jdutchak** [comment]
do you not need to pass a tag in 0.4.0 ?

**Comment by paulmillr** [comment]
huh? it was never needed, not even in 0.1.4

**Comment by natew** [comment]
For some reason I get this in production on a node:22.4-slim dockerfile

![Image](https://github.com/user-attachments/assets/e676c550-bb47-4a84-a38e-2a6dca4ee432)

**Comment by paulmillr** [comment]
any specific test vector you could share?

**Comment by natew** [comment]
I'm trying to debug, I can repro it locally now just building it to production, but its in a private repo. Using better-auth, tried a bunch of keys, changing various things. Tried logging before `invalid tag` and the passedTag and tag look identical at least the bun log UInt8Array shows the same thing.

Tried setting resolutions to upgrade from 0.6 to 1.2 and now I get this, not sure if this is at all relevant.

![Image](https://github.com/user-attachments/assets/04713e92-2a7e-4a4e-b3cd-5b1706cbad28)
