### ISSUE TITLE
Utils functions for base64 conversion 

### ISSUE THREAD

**Issue by kaladivo** [paulmillr/noble-ciphers#17]
Sometimes it makes sense to store keys / cypher in base64 format instead of hex, it would be nice to have utility function for that. The same way as there are hex conversion functions (`hexToBytes` and `bytesToHex` in `@noble/ciphers/utils`).

This is useful especially if we want to store encrypted data in database since base64 string is shorter.

**Comment by paulmillr** [comment]
https://github.com/paulmillr/scure-base#usage
