### ISSUE TITLE
Cannot resolve webcrypto using typescript

### ISSUE THREAD

**Issue by devnomic** [paulmillr/noble-ciphers#20]
Screenshot:
<img width="959" alt="Screenshot 2024-01-28 at 18 36 10" src="https://github.com/paulmillr/noble-ciphers/assets/101681592/cd2d119b-4ff4-44be-938d-87097d64c769">

**Comment by paulmillr** [comment]
Your bundler must support import map, which is specified in package.json.

**Comment by devnomic** [comment]
I managed to import it using
`import { managedNonce, randomBytes } from "@noble/ciphers/webcrypto/utils";`

It seems 0.4.1 code is different from main branch
