### ISSUE TITLE
`isPlainObject` returns `false` incorrectly 

### ISSUE THREAD

**Issue by ocavue** [paulmillr/noble-ciphers#21]
The [`isPlainObject`](https://github.com/paulmillr/noble-ciphers/blob/b58c93632469ab2ed9b6ead74dfcc019f7524b68/src/utils.ts#L164-L166) function returns `false` when it's running in a NextJS API function. Here is a minimal reproduction:

1. https://stackblitz.com/github/issueset/noble-nextjs-error?file=lib%2Frun.js
2. Append `/api/hello` in the internal browser window
3. Get the following error: `⨯ node_modules/@noble/ciphers/esm/utils.js (143:14) @ checkOpts ⨯ options must be object or undefined`

<img width="724" alt="image" src="https://github.com/paulmillr/noble-ciphers/assets/24715727/18a0e50d-46c6-43cc-9dc5-5ee0a80e4dd0">

---

Although I don't know why `isPlainObject` doesn't work in this case, it seems that a popular  NPM package is better than a hand-written version for this feature. Maybe we can use https://www.npmjs.com/package/is-plain-object or https://www.npmjs.com/package/is-plain-obj.

**Comment by ocavue** [comment]
I found the reason. 

1. I'm running the "Next.js Edge Runtime" to run the serverless functions.
Docs: https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes
1. When I run `next dev` (in dev mode) or `next build && next start` (in prod mode) locally, Next.js still uses Node.js to execute my serverless functions. Next.js uses Node.js VM to provide isolated scopes for each serverless function. 
1. One of the weird things with Node.js VM is that `obj instanceof Object` is false, and people complained about it. Issue link: https://github.com/vercel/next.js/issues/38184
1. As a workaround, Vercel Edge Runtime proxies `globalThis.Object`, and overrides the `Symbol.hasInstance` getter. Code link: https://github.com/vercel/edge-runtime/blob/fd3fd3330d0be325578668ef8e4beac69206d900/packages/vm/src/edge-vm.ts#L79-L145
1. Since `Object` is a proxy now, `obj.constructor === Object` in our code always returns `false`.

It seems that Next.js and Vercel are not doing something "malicious". 

One thing to notice is that `globalThis.Object` is not the only thing they proxy. They also proxy `Uint8Array` and something more (see my code link above). That means, while we can still use `a instanceof Uint8Array` in noble-ciphers, we cannot use `a.constructor === Uint8Array`.

**Comment by paulmillr** [comment]
Solved in 2e49a16.
