### ISSUE TITLE
Support for 64 byte (512 bit) AES-SIV keys

### ISSUE THREAD

**Issue by httpjamesm** [paulmillr/noble-ciphers#37]
According to RFC 5297, AES-SIV keys are supposed to be 64 bytes in length, such as a concatenated master key and MAC key, however, the siv() function rejects anything over 32 bytes. Is there a way to pass in 64 bytes of data, or does it need to be updated?

**Comment by paulmillr** [comment]
We don't support SIV, only GCM-SIV which is different.

**Comment by overheadhunter** [comment]
shouldn't the API be renamed then? Just fell for it being GCM-SIV, also currently it leaves no room to eventually add SIV-support.

**Comment by paulmillr** [comment]
Maybe. Why is SIV useful? What makes it more useful than GCM-SIV?

**Comment by overheadhunter** [comment]
> Maybe. Why is SIV useful? What makes it more useful than GCM-SIV?

This is less about newly created standalone apps but rather applications that seek to be compatible to existing data/standards/protocols that facilitate SIV.

**Comment by paulmillr** [comment]
05a6534 renames siv to gcmsiv unless someone has a better naming idea.
