### ISSUE TITLE
Error: 'Cannot encrypt() twice with same key + nonce' after Updating to 1.1.0

### ISSUE THREAD

**Issue by gtolarc** [paulmillr/noble-ciphers#46]
Since updating from version 1.0.0 to 1.1.0, the following error occurs during aes.encrypt. It was working perfectly before. What could be the cause?

'cannot encrypt() twice with same key + nonce'

**Comment by paulmillr** [comment]
You can't reuse key and nonce between two different encryptions. That would break the encryption.

Also you can still do this:

```js
aes(key, nonce).encrypt()
aes(key, nonce).encrypt()
```

**Comment by gtolarc** [comment]
@paulmillr Are you saying that it shouldn't be used like this? It actually causes an error.

const aes = cbc(key, iv);
aes.encrypt('123');
aes.encrypt('456');

**Comment by paulmillr** [comment]
Yes, this is invalid.
