### ISSUE TITLE
RangeError when decrypting chacha20poly1305: start offset of Uint32Array should be a multiple of 4

### ISSUE THREAD

**Issue by hazae41** [paulmillr/noble-ciphers#7]
I was trying to decrypt 2246 bytes (Uint8Array) with 12 bytes IV and got the error

```tsx
chacha20poly1305(key, iv).decrypt(bytes)
```

> RangeError: start offset of Uint32Array should be a multiple of 4

It also happens if I force `.slice()` to copy to a new buffer

```tsx
chacha20poly1305(key, iv).decrypt(bytes.slice())
```

Using Stablelib it works fine

```tsx
new ChaCha20Poly1305(key).open(iv, cipher)
```

**Comment by paulmillr** [comment]
for now either key or iv need to be their own array and now a subarray: `chacha20poly1305(key.slice(), iv.slice())` should be a workaround

**Comment by hazae41** [comment]
Thanks, it works

**Comment by paulmillr** [comment]
Fixed
