### ISSUE TITLE
Implement AES in pure JS

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/noble-ciphers#8]
That would be a good alternative to native crypto.subtle methods which are not supported in RN and could provide a fine low-level primitive for stuff like SIV

**Comment by steida** [comment]
@paulmillr For React Native, there is https://github.com/margelo/react-native-quick-crypto, which is C++ OpenSSL, but it lacks SubtleCrypto. I think a Polyfill for AES based on margelo/react-native-quick-crypto (or crypto-browserify) would be enough.

**Comment by paulmillr** [comment]
We won't specifically target RN and develop a polyfill. Generic AES for all platforms sounds good tho
